# Generated by Django 2.1.5 on 2019-10-31 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='host_name',
            new_name='hostname',
        ),
    ]
