# Generated by Django 2.1.5 on 2019-11-01 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20191031_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connection',
            options={'verbose_name': '连接表', 'verbose_name_plural': '连接表'},
        ),
        migrations.RemoveField(
            model_name='asset',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='latest_date',
        ),
        migrations.RemoveField(
            model_name='server',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='server',
            name='latest_date',
        ),
        migrations.AlterField(
            model_name='asset',
            name='cabinet',
            field=models.CharField(max_length=128, verbose_name='机柜'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='cmdb.TreeNode', verbose_name='节点'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='authed',
            field=models.BooleanField(default=False, help_text='是否建立了基于密钥的连接', verbose_name='是否认证'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='password',
            field=models.CharField(max_length=1024, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='port',
            field=models.PositiveIntegerField(verbose_name='sshd监听端口号'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='user',
            field=models.CharField(max_length=64, verbose_name='SSH用户'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorys', to='cmdb.Server', verbose_name='服务器'),
        ),
        migrations.AlterField(
            model_name='server',
            name='hostname',
            field=models.CharField(max_length=128, verbose_name='主机名'),
        ),
    ]
