# Generated by Django 2.1.5 on 2019-11-01 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20191101_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='name',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='设备名称'),
        ),
    ]
