# Generated by Django 2.1.5 on 2019-11-06 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_inventorypool'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variable2Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, verbose_name='变量名')),
                ('val', models.CharField(max_length=512, verbose_name='变量值')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv2vars', to='cmdb.Inventorypool', verbose_name='所属组')),
            ],
            options={
                'verbose_name': 'Ansible 组变量表',
                'verbose_name_plural': 'Ansible 组变量表',
                'db_table': 'variable_group',
            },
        ),
        migrations.CreateModel(
            name='Variable2Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='', max_length=64, verbose_name='变量名')),
                ('val', models.CharField(default='', max_length=512, verbose_name='变量值')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server2vars', to='cmdb.Server', verbose_name='所属主机')),
            ],
            options={
                'verbose_name': 'Ansible 主机变量表',
                'verbose_name_plural': 'Ansible 主机变量表',
                'db_table': 'variable_host',
            },
        ),
    ]
